---
# Defines tasks applicable across all hosts

- name: Install System sudoers file
  template: src=sudoers.j2
            dest=/etc/sudoers
            owner=root
            group=root
            mode=0440

- name: Install minimum packages
  yum: name={{ item }} state=present
  with_items:
    - sudo
    - tmux
    - wget
    - zip
    - unzip
    - xz-libs
    - zlib
    - openssl
    - curl
    - expat
    - libuuid
    - mlocate
    - iftop
    - htop
    - yum-plugin-fastestmirror
    - ncurses
    - tree

