---
# Defines tasks applicable across all hosts

- name: Install minimum packages
  yum: name={{ item }} state=present
  with_items:
    - sudo
    - screen
    - wget
    - xz-libs
    - zlib
    - openssl
    - curl
    - expat
    - libuuid
    - mlocate
    - iftop
    - htop
    - yum-plugin-fastestmirror
