---
# Embedded development
# This currently includes configuration for AVR development and Embedded ARM development
# but these may be broken out separately in the future

- include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
