---
# Embedded Development for Ubuntu
#
- name: Make sure apt-get is up to date
  apt: update_cache=yes

- name: Install minimum packages
  apt: name={{ item }} state=present
  with_items:
    - parted
    - minicom
    - u-boot-tools
    - dosfstools

- name: Install Embedded Python packages
  pip: name={{ item }}
  with_items:
    - pyusb
    - pyserial
