---
# file: roles/common/tasks/rbenv.yml
#
# git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
# echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
# echo 'eval "$(rbenv init -)"' >> ~/.bashrc
# git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
#

##################################################
# Centos
- name: Remove old Ruby installs
  yum: name={{ item }} state=removed
  with_items:
    - ruby
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Fetch rbenv
  git: repo=https://github.com/sstephenson/rbenv.git
       dest=~/.rbenv
  register: get_rbenv_result
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Setup PATH for rbenv
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/{{ shell_rc }}
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: rbenv init
  shell: echo 'eval "$(rbenv init -)"' >> ~/{{ shell_rc }}
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Ruby {{ ruby_version }}
  shell: rbenv install {{ ruby_version }}
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set global Ruby {{ ruby_version }}
  shell: rbenv global {{ ruby_version }}
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set rehash rbenv
  shell: rbenv rehash
  when: get_rbenv_result.changed
  sudo: False
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

##################################################
# Ubuntu

- name: Install minimum packages
  apt: name={{ item }} state=present
  with_items:
    - rbenv
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
