---
# file: roles/common/tasks/python_27.yml
#
# wget http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz
# tar xvzf Python-2.7.6.tgz
# cd Python-2.7.6
# ./configure --prefix=/usr/local
# make
# make altinstall
#

- name: Download Python
  get_url: url=http://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz
           dest=/tmp/Python-{{ python_version }}.tgz
  register: get_url_result

- name: Untar Python
  shell: tar -xvzf /tmp/Python-{{ python_version }}.tgz
         chdir=/tmp
  when: get_url_result.changed

- name: Configure Python
  shell: ./configure --prefix=/usr/local
         chdir=/tmp/Python-{{ python_version }}
  when: get_url_result.changed

- name: Build Python
  shell: make altinstall
         chdir=/tmp/Python-{{ python_version }}
  when: get_url_result.changed


