---
# Add Clang and LLVM Compiler chain

- name: Install Clang/LLVM packages
  yum: name={{ item }} state=present
  with_items:
    - clang
    - llvm
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Clang/LLVM packages
  apt: name={{ item }} state=present
  with_items:
    - clang
    - llvm
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
