---
# Defines tasks applicable across all hosts

- name: Install minimum packages
  apt: name={{ item }} state=present
  with_items:
    - ccache
    - distcc
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install minimum packages
  yum: name={{ item }} state=present
  with_items:
    - ccache
    - distcc
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create Local CCache directory
  shell: mkdir -p {{ ccache_directory }}

- name: Change ownership
  shell: chown -R {{ user }}:{{ user }} {{ ccache_directory }}
