---
# file: roles/common/tasks/git.yml
#
# git clone git://github.com/git/git.git
# make --prefix=/usr/local
# make install

- name: Fetch git
  git: repo=git://github.com/git/git.git
       dest=/tmp/git
       version={{ git_version }}
       accept_hostkey=True
  register: result

- name: Build All
  shell: make prefix=/usr/local all
         chdir=/tmp/git
  when: result.changed

- name: Build & Install git
  shell: make prefix=/usr/local install
         chdir=/tmp/git
  when: result.changed

- name: Remove tools that have been superseded
  yum: name={{ item }} state=removed
  with_items:
    - git
    - git-svn
  when: result.changed
