---
# Common Developer configuration

- include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: thrift.yml tags=developer
- include: oh-my-zsh.yml tags=developer
- include: clang.yml tags=developer
- include: distr_compile.yml tags=developer
- include: tig.yml tags=git,developer
- include: poco.yml tags=poco,developer

#- name: Set Zsh as default shell
#  shell: chsh -s $(which zsh)
#  when: zsh_result.changed
#  sudo: False
