---
# file: roles/common/tasks/tig.yml
#
# wget http://jonas.nitro.dk/tig/releases/tig-2.0.tar.gz
# tar xvzf tig-2.0.tar.gz
# cd tig-2.0
# ./configure --prefix=/usr/local
# make
# make install

- name: Remove default tig package
  yum: name=tig state=absent
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Remove default tig package
  apt: name=tig state=absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Download tig {{ tig_version }}
  get_url: url=http://jonas.nitro.dk/tig/releases/tig-{{ tig_version }}.tar.gz
           dest=/tmp/tig-{{ tig_version }}.tar.gz
  register: get_url_result

- name: Untar tig {{ tig_version }}
  shell: tar -xvzf /tmp/tig-{{ tig_version }}.tar.gz
         chdir=/tmp
  when: get_url_result.changed

- name: Configure tig {{ tig_version }}
  shell: ./configure --prefix=/usr/local
         chdir=/tmp/tig-{{ tig_version }}
  when: get_url_result.changed

- name: Build and Install tig {{ tig_version }}
  shell: make install
         chdir=/tmp/tig-{{ tig_version }}
  when: get_url_result.changed


