---
- hosts: all
  sudo: True

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_os_family }}.yml

  roles:
    - { role: yum_repos,  when: ansible_distribution == 'CentOS' }
    - { role: yum_repos,  when: ansible_distribution == 'Red Hat Enterprise Linux' }

    - common
    - common_dev
    - ruby_dev
    - python_dev
    - embedded_dev
